sudo: required
language: csharp
dist: xenial
mono: none
dotnet: 2.2
os: linux
solution: CICDTools.sln
install:
  - dotnet restore
  - choco install codecov
  - dotnet tool install --global coverlet.console
branches:
  only:
    - master
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
services:
  - xvfb
script:
  - dotnet restore
  - dotnet build
  - dotnet test CICDTools.Tests/CICDTools.Tests.csproj
  - coverlet ./Lottery.Models.Test/bin/Debug/netcoreapp2.2/Lottery.Models.Test.dll --target "dotnet" --targetargs "test ./Lottery.Models.Test/Lottery.Models.Test.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover" --format opencover --output ./testResults/lotteryApp.Model.xml
after_script:
  - bash <(curl -s https://codecov.io/bash)