sudo: required
language: csharp
dist: xenial
mono: none
dotnet: 2.2
os: linux
solution: CICDTools.sln
install:
  - dotnet restore
  - dotnet tool install -g dotnet-sonarscanner
  - dotnet tool install --global coverlet.console
  - Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  - choco install jre8
  - choco install codecov
branches:
  only:
    - master
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
services:
  - xvfb
script:
  - dotnet restore -verbosity quiet
  - dotnet build -verbosity quiet
  - dotnet test CICDTools.Tests/CICDTools.Tests.csproj
