sudo: required
language: csharp
dist: xenial
mono: none
dotnet: 2.2
os: linux
solution: CICDTools.sln
install:
  - dotnet restore
branches:
  only:
    - master
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
services:
  - xvfb
script:
  - mono ../tools/sonar/SonarQube.Scanner.MSBuild.exe begin /n:NGenerics /k:ngenerics-github /d:sonar.login=${SONAR_TOKEN} /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vstest.reportsPaths="*/TestResults/.trx" /v:"2.0"
  - dotnet restore -verbosity quiet
  - dotnet build -verbosity quiet
  - dotnet test CICDTools.Tests/CICDTools.Tests.csproj 
after_script:
  - bash <(curl -s https://codecov.io/bash)
