sudo: required
language: csharp
dist: xenial
mono: none
dotnet: 2.2
os: linux
solution: CICDTools.sln
install:
  - dotnet restore
branches:
  only:
    - master
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
services:
  - xvfb
script:
  - dotnet restore
  - dotnet build
  - dotnet test CICDTools.Tests/CICDTools.Tests.csproj
after_script:
  - bash <(curl -s https://codecov.io/bash)