
image: Visual Studio 2019

branches:
  only:
  - master
#environment:
#  SONAR_TOKEN:
#    secure: 1le4hKhDyj6UuukBpuVK6a7LQT98MINrDKnDilQI8HhW5sYHWKzZnROmphFDHc2/
#  CODECOV_TOKEN:
#    secure: Aq9F+tLDv0Jh091xMqqa+bve7b6FgoXllUJ2pPRLHafcvHH9euNb478dOeuEsTLi

skip_commits:
  files:
  - README.md

before_build:
  - choco install codecov
  #- choco install xunit
  - dotnet tool install -g dotnet-sonarscanner
  - dotnet tool install --global coverlet.console
  - nuget restore

build:
  project: CICDTools.sln
  verbosity: minimal

after_build:
#  - ps: dotnet-sonarscanner begin /k:"rsmivb_CICDTools" /o:"rsmivb-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:SONAR_TOKEN"
#  - dotnet build .\CICDTools\CICDTools.csproj
#  - ps: dotnet-sonarscanner end /d:sonar.login="$env:SONAR_TOKEN"
test_script:
  - coverlet ./CICDTools.Tests/bin/Debug/netcoreapp2.2/CICDTools.Tests.dll --target "dotnet" --targetargs "test ./CICDTools.Tests/CICDTools.Tests.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover" --format opencover --output ./testResults/CICDTools.Tests.xml
  - ps: codecov -f .\testResults\CICDTools.Tests.xml -t $env:CODECOV_TOKEN