
image: Visual Studio 2019

branches:
  only:
  - master
environment:
   SONAR_TOKEN:
    secure: Vgk2JJs/E58YhjR1gLjj0Au0LKs4+GWjuVqgHVQmPP+kV2WN2hylsxkPii43ITVC
   CODECOV_TOKEN:
     secure: 0xbrDlIAs6NDcEgALFNFrp6TmfkEU1dzaAMPSjbt3VxD4L+evvkpx+FuYOXfl3Dp

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
skip_commits:
  files:
  - README.md

before_build:
  - choco install jre8
  - choco install codecov
  - dotnet tool install -g dotnet-sonarscanner
  - dotnet tool install --global coverlet.console
  - nuget restore --verbosity quiet

build:
  project: CICDTools.sln
  verbosity: minimal
test_script:
  - ps: $env:JAVA_HOME = "C:\Program Files\Java\jre1.8.0_211\"
  - dotnet-sonarscanner begin /k:"rsmivb_CICDTools" /o:"rsmivb-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:SONAR_TOKEN"
  - dotnet build CICDTools.sln -v minimal
  - coverlet ./CICDTools.Tests/bin/Debug/netcoreapp2.2/CICDTools.Tests.dll --target "dotnet" --targetargs "test ./CICDTools.Tests/CICDTools.Tests.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover" --format opencover --output ./testResults/CICDTools.Tests.xml
  - dotnet-sonarscanner end /d:sonar.login="$env:SONAR_TOKEN"
  - ps: codecov -f .\testResults\CICDTools.Tests.xml -t $env:CODECOV_TOKEN
